# -*- coding: utf-8 -*-
"""FFP_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZSAlcVL9EevI0hpzwl3cifVRyBtpPQj7
"""

from flask import Flask, render_template, request
from flask_wtf import FlaskForm
from ffp_form import DataEntryForm
from ffp_feature_transformation import transform_feature
from joblib import load
import numpy as np


app = Flask(__name__)
app.config['SECRET_KEY']='406cdbd39813edf0971d172ecca5a610'


@app.route("/", methods = ['GET','POST'])
def home():
  
  form = DataEntryForm()
  if request.method == 'POST':

    if form.is_submitted():

      user_input = request.form.to_dict()
      try:

        if user_input['Source'] == user_input['Destination']:
          return render_template('ffp_index.html',form=form, value_low = '', 
                              value_high = '',rupees='', fallback_text='Source and Destination Should not be the Same')

        else:
          y = transform_feature(user_input)
          model = load('Flight_Fare_Prediction_Model.pkl')
          predicted_flight_fare = model.predict([y])
          predicted_flight_fare = np.round(predicted_flight_fare)
          low = (predicted_flight_fare / 100) * 5     # 5% decrease in Fare
          high = (predicted_flight_fare / 100) * 15   # 15% increase in Fare 
          value_low = np.round(predicted_flight_fare - low)
          value_high = np.round(predicted_flight_fare + high)
          
          return render_template('ffp_index.html',form=form, value_low = int(value_low), 
                                value_high = int(value_high), rupees='Rs', fallback_text='')
      
      except:

        return render_template('ffp_index.html', form=form, value_low='', value_high='', rupees="", fallback_text='Something Went Wrong')

   
  return render_template('ffp_index.html', form=form, value_low=None, value_high=None, rupees="", fallback_text='')

if __name__ == '__main__':
	app.run(debug=True)