# -*- coding: utf-8 -*-
"""ffp_form.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEAV_EUH43FYNIqqHhEFlFhdV-eLUr_J
"""

from flask_wtf import FlaskForm

from wtforms import SubmitField,SelectField,FloatField
from wtforms.fields import DateField
from wtforms.validators import DataRequired

class DataEntryForm(FlaskForm):

  airline = ['Air Asia', 'Air India', 'GoAir', 'IndiGo', 'Jet Airways', 
                    'Jet Airways Business', 'Multiple carriers', 'Multiple carriers Premium economy', 
                    'SpiceJet', 'Trujet', 'Vistara', 'Vistara Premium economy']

  source = ['Bangalore', 'Chennai', 'Delhi', 'Kolkata', 'Mumbai']

  destination = ['Bangalore', 'Cochin', 'Delhi', 'Hyderabad', 'Kolkata']

  stop = ['non-stop', '1 stop', '2 stops' ,'3 stops', '4 stops']

  Airline = SelectField('Select AirLine Service ', choices=airline)
  Source = SelectField('Select Source ', choices=source)
  Destination = SelectField('Select Destination ', choices=destination)
  Total_Stops = SelectField('Select Total Stops ', choices=stop )
  Departure_Date = DateField('Departure Date ', format='%m/%d/%Y', validators=[DataRequired()])

  submit = SubmitField(' Calculate Flight Fare ')



